-- local colorscheme = "rose-pine"
-- local colorscheme = "gruvbox"
-- local colorscheme = "tokyonight-storm"
-- local colorscheme = "tokyonight-day"
-- local colorscheme = "tokyonight-moon"
-- local colorscheme = "tokyonight-night"
-- local colorscheme = "catppuccin"
-- local colorscheme = "catppuccin-latte"
-- local colorscheme = "catppuccin-frappe"
-- local colorscheme = "catppuccin-macchiato"
-- local colorscheme = "catppuccin-mocha"
local colorscheme = "kanagawa-dragon"
-- local colorscheme = "kanagawa-wave"
-- local colorscheme = "onedark"
-- local colorscheme = "onedark_vivid"
-- local colorscheme = "onedark_dark"
-- local colorscheme = "nightfly"
-- local colorscheme = "cyberdream"
-- local colorscheme = "nordic"
-- local colorscheme = "melange"
-- local colorscheme = "poimandres"
-- local colorscheme = "mellifluous"
-- local colorscheme = "everforest"
-- local colorscheme = "crimson_moonlight"
-- local colorscheme = "vague"
-- local colorscheme = "pastelnight"
-- local colorscheme = "lavish"
-- local colorscheme = "sunset_cloud"
-- local colorscheme = "radioactive_waste"
-- local colorscheme = "forest_stream"
-- local colorscheme = "github_dark"
-- local colorscheme = "github_dark_default"
-- local colorscheme = "github_dark_dimmed"
-- local colorscheme = "github_dark_high_contrast"
-- local colorscheme = "github_dark_colorblind"
-- local colorscheme = "github_dark_tritanopia"

local status_ok, _ = pcall(vim.cmd, "colorscheme " .. colorscheme)
if not status_ok then
  return
end
